### ISSUE TITLE
update CGAL

### ISSUE THREAD

**Issue by thomasp85** [dickoa/cgalh#2]
I don't know if this is possible to get into the current release process but I have run into some issues with the straight skeleton package in the version included in cgalh. If time permits an update to CGAL 5.5 would be amazing

**Comment by dickoa** [comment]
Hi @thomasp85 
I think it's still possible. Pushing new version today.

**Comment by thomasp85** [comment]
Amazing - thanks

**Comment by thomasp85** [comment]
Don't know how you plan to version cgalh but maybe give it the same version as the version of CGAL included. I believe BH does the same for boost

**Comment by dickoa** [comment]
I added the 5.5.1 header files from CGAL two months ago (cgalh v5.5.1), but I'll double-check again to make sure that I had the right headers file.

**Comment by thomasp85** [comment]
hum... it seems my computer was using an old version - sorry about the noise

**Comment by dickoa** [comment]
Great! I was worried that I copied the wrong version of CGAL in the package. 
I'll add a script in inst or data-raw to pull it automatically and make sure that we always have the right version.
Thanks
